<?php

declare(strict_types=1);

return [
    '/views/index.php' => 'resources/views/pages/acesso/login.php',
    '/views/src/pages/alunos/home.php' => 'resources/views/pages/aluno/home.php',
    '/views/src/pages/alunos/jogos.php' => 'resources/views/pages/aluno/jogos.php',
    '/views/src/pages/alunos/login.php' => 'resources/views/pages/aluno/login.php',
    '/views/src/pages/alunos/modalidade.php' => 'resources/views/pages/aluno/modalidade.php',
    '/views/src/pages/alunos/perfil.php' => 'resources/views/pages/aluno/perfil.php',
    '/views/src/pages/alunos/ranking.php' => 'resources/views/pages/aluno/ranking.php',
    '/views/src/pages/alunos/termos.php' => 'resources/views/pages/aluno/termos.php',
    '/views/src/pages/categorias.php' => 'resources/views/pages/eventos/categorias.php',
    '/views/src/pages/chaveamento_arvore.php' => 'resources/views/pages/competicoes/chaveamento.php',
    '/views/src/pages/colaboradores.php' => 'resources/views/pages/acesso/colaboradores.php',
    '/views/src/pages/dashboard.php' => 'resources/views/pages/eventos/dashboard.php',
    '/views/src/pages/edicao_agenda.php' => 'resources/views/pages/eventos/configurar-agenda.php',
    '/views/src/pages/edicao_arrecadacao.php' => 'resources/views/pages/eventos/configurar-arrecadacao.php',
    '/views/src/pages/edicao_categorias.php' => 'resources/views/pages/eventos/configurar-categorias.php',
    '/views/src/pages/edicao_equipes.php' => 'resources/views/pages/eventos/configurar-equipes.php',
    '/views/src/pages/edicao_locais.php' => 'resources/views/pages/eventos/configurar-locais.php',
    '/views/src/pages/edicao_modalidades.php' => 'resources/views/pages/eventos/configurar-modalidades.php',
    '/views/src/pages/edicao_pontuacao.php' => 'resources/views/pages/eventos/configurar-pontuacao.php',
    '/views/src/pages/edicao_resumo.php' => 'resources/views/pages/eventos/configurar-resumo.php',
    '/views/src/pages/edicao_turmas.php' => 'resources/views/pages/eventos/configurar-turmas.php',
    '/views/src/pages/elenco_equipe.php' => 'resources/views/pages/competicoes/elenco-equipe.php',
    '/views/src/pages/equipe_alunos.php' => 'resources/views/pages/competicoes/equipe-alunos.php',
    '/views/src/pages/home.php' => 'resources/views/pages/eventos/lista.php',
    '/views/src/pages/jogos.php' => 'resources/views/pages/competicoes/placar.php',
    '/views/src/pages/jogos_lista.php' => 'resources/views/pages/competicoes/jogos.php',
    '/views/src/pages/modalidade_detalhes.php' => 'resources/views/pages/competicoes/modalidade-detalhes.php',
    '/views/src/pages/modalidades.php' => 'resources/views/pages/competicoes/modalidades.php',
    '/views/src/pages/ocorrencias.php' => 'resources/views/pages/disciplina/ocorrencias.php',
    '/views/src/pages/perfil.php' => 'resources/views/pages/acesso/perfil.php',
    '/views/src/pages/ranking.php' => 'resources/views/pages/resultados/ranking.php',
    '/views/src/pages/turma_alunos.php' => 'resources/views/pages/participantes/turma-alunos.php',
    '/views/src/pages/turmas.php' => 'resources/views/pages/participantes/turmas.php',
];
