<?php

declare(strict_types=1);
return [
    '/login' => 'resources/views/pages/acesso/login.php',
    '/aluno/inicio' => 'resources/views/pages/aluno/home.php',
    '/aluno/jogos' => 'resources/views/pages/aluno/jogos.php',
    '/aluno/login' => 'resources/views/pages/aluno/login.php',
    '/aluno/modalidades' => 'resources/views/pages/aluno/modalidade.php',
    '/aluno/perfil' => 'resources/views/pages/aluno/perfil.php',
    '/aluno/ranking' => 'resources/views/pages/aluno/ranking.php',
    '/aluno/termos' => 'resources/views/pages/aluno/termos.php',
    '/categorias' => 'resources/views/pages/eventos/categorias.php',
    '/chaveamento' => 'resources/views/pages/competicoes/chaveamento.php',
    '/colaboradores' => 'resources/views/pages/acesso/colaboradores.php',
    '/painel' => 'resources/views/pages/eventos/dashboard.php',
    '/edicoes/agenda' => 'resources/views/pages/eventos/configurar-agenda.php',
    '/edicoes/arrecadacao' => 'resources/views/pages/eventos/configurar-arrecadacao.php',
    '/edicoes/categorias' => 'resources/views/pages/eventos/configurar-categorias.php',
    '/edicoes/equipes' => 'resources/views/pages/eventos/configurar-equipes.php',
    '/edicoes/locais' => 'resources/views/pages/eventos/configurar-locais.php',
    '/edicoes/modalidades' => 'resources/views/pages/eventos/configurar-modalidades.php',
    '/edicoes/pontuacao' => 'resources/views/pages/eventos/configurar-pontuacao.php',
    '/edicoes/resumo' => 'resources/views/pages/eventos/configurar-resumo.php',
    '/edicoes/turmas' => 'resources/views/pages/eventos/configurar-turmas.php',
    '/equipes/alunos' => 'resources/views/pages/competicoes/equipe-alunos.php',
    '/equipes/elenco' => 'resources/views/pages/competicoes/elenco-equipe.php',
    '/edicoes' => 'resources/views/pages/eventos/lista.php',
    '/jogos/placar' => 'resources/views/pages/competicoes/placar.php',
    '/jogos' => 'resources/views/pages/competicoes/jogos.php',
    '/modalidades/detalhes' => 'resources/views/pages/competicoes/modalidade-detalhes.php',
    '/modalidades' => 'resources/views/pages/competicoes/modalidades.php',
    '/ocorrencias' => 'resources/views/pages/disciplina/ocorrencias.php',
    '/perfil' => 'resources/views/pages/acesso/perfil.php',
    '/ranking' => 'resources/views/pages/resultados/ranking.php',
    '/turmas/alunos' => 'resources/views/pages/participantes/turma-alunos.php',
    '/turmas' => 'resources/views/pages/participantes/turmas.php',
];
