CREATE TABLE `pontuacoes_podio` (
  `id_pontuacao` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_interclasse` int(11) NOT NULL,
  `id_modalidade` int(11) NOT NULL,
  `posicao` tinyint(4) NOT NULL,
  `id_turma` int(11) NOT NULL,
  `id_equipe` int(11) DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `id_jogo` int(11) DEFAULT NULL,
  `pontos` int(11) NOT NULL,
  `ativo` tinyint(4) NOT NULL DEFAULT 1,
  `origem_registro` varchar(24) NOT NULL,
  `atualizado_em` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_pontuacao`),
  UNIQUE KEY `uk_podio_edicao_modalidade_posicao` (`id_interclasse`,`id_modalidade`,`posicao`),
  KEY `idx_podio_turma_ativo` (`id_turma`,`ativo`),
  KEY `idx_podio_jogo` (`id_jogo`),
  CONSTRAINT `fk_podio_interclasse` FOREIGN KEY (`id_interclasse`) REFERENCES `interclasses` (`id_interclasse`),
  CONSTRAINT `fk_podio_modalidade` FOREIGN KEY (`id_modalidade`) REFERENCES `modalidades` (`id_modalidade`),
  CONSTRAINT `fk_podio_turma` FOREIGN KEY (`id_turma`) REFERENCES `turmas` (`id_turma`),
  CONSTRAINT `fk_podio_equipe` FOREIGN KEY (`id_equipe`) REFERENCES `equipes` (`id_equipe`) ON DELETE SET NULL,
  CONSTRAINT `fk_podio_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id_usuario`) ON DELETE SET NULL,
  CONSTRAINT `fk_podio_jogo` FOREIGN KEY (`id_jogo`) REFERENCES `jogos` (`id_jogo`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
